apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: myapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql 
  strategy:
    type: Recreate
  template:
    metadata:
      name: myapp-mysql
      labels: 
        app: mysql
    spec:
        containers:
          - name: mysql  
            image: mysql:5.6 
            env:
              - name: MYSQL_ROOT_PASSWORD 
                valueFrom:
                  secretKeyRef:
                    name: user-db-secret 
                    key: db-password
            ports:
              - containerPort: 3306 
                name: mysql 
            volumeMounts:
            - name: mysql-persistent-volume  
              mountPath: /var/lib/mysql 
            - name: usermgmt-dbscript 
              mountPath: /docker-entrypoint-initdb.d 
        volumes: 
          - name: mysql-persistent-volume 
            persistentVolumeClaim:
              claimName: user-data-pvc
          - name: usermgmt-dbscript
            configMap: 
              name: user-db-creation-script